### PR TITLE
Add repeats for useradd command on shared host provision

### PR DESCRIPTION
**Pull request by mshaposhnik**
Sometimes on shared servers there is a possible conflict adding/removing the users, so  some operations getting 
`useradd: cannot lock /etc/passwd; try again later` error.   This PR adds some retires to the operation.

Jira bug https://issues.redhat.com/browse/KFLUXBUGS-1532

### CODE REVIEW

**Comment by hugares** [comment]
LGTM

**Comment by hugares** [comment]
@mshaposhnik I see the default merge strategy for this repo is to create a merge commit, so we will end up with the "fixup" in the git history. Can you squash the Fixup commit into the other one

**Comment by mshaposhnik** [comment]
@ifireball i have to re-done the repeating, since it turns out that it is unable to send unevaulated variables inside the script, all variables are evaulated during tekton task run.  PTAL again.

**Review by ifireball — APPROVED** [review]
lgtm

**Comment by ifireball** [comment]
@mshaposhnik LMG if this is ready to merge

**Comment by mshaposhnik** [comment]
@ifireball  it is ready

**Pull request merged**
