### PR TITLE
Integration KFLUXINFRA-1143 - refining the post-merge SeaLights scan on merged main (no test runs)

### PR DESCRIPTION
**Pull request by meyrevived**
Dealing with PR contexts again because of SeaLights need for an agent token. Because the post-merge action (pull_request on a closed pull request) is still running in the context of the PR branch (the forked repository that has no access to the SeaLights token stored as a repository token on the main repository) this workflow needs to be changed to just be a stub workflow that triggers a workflow_run (committed now) that will run only if it's in the context of the main repository.

In this PR:
1. Changes to the workflow that runs a SeaLights scan on a merged main so that it won't be triggered on its own.
2. Removal of the extra log writes for testing SeaLights noticing code changes, so that Eran's [PR](https://gitlab.cee.redhat.com/konflux/infra/-/merge_requests/297) can run be merged

### CODE REVIEW

**Comment by mshaposhnik** [comment]
Could you please make the PR heading a little more descriptive? It will be hard to understood after some time what was changed and why.

**Comment by meyrevived** [comment]
@mshaposhnik  - done
@eisraeli:
1. It is in the title and the commit message
2. The PR can't include all the work because the workflow that is committed here needs to be in the main repository before the second workflow that triggers it is PR-ed. The reason is in the SeaLights token for their agent. It's kept as a repository secret on the main MPC repo. A forked branch can't have access to the main repo's secrets in a pull_request, which is why I'm committing them in two separate PRs - if I commit both workflows, the workflow I'm committing now will run in the forked repo context and will not have access to the repo secret. It's the same reason why I had to split the before-merge testing with SeaLights scan to two workflows a new [pull_request_target](https://github.com/konflux-ci/multi-platform-controller/blob/main/.github/workflows/sealights-mpc-test-ci.yaml) workflow and add a trigger to it in go-ci.yaml (aka, the main CI workflow for MPC)
3. I have done in the past and will do so now
4. If I have a short commit message, people will ask me why I did XYZ, and in this specific commit I need a very long explenation like I did in answer to item #2 
5. Hugo made the connection and put your PR on hold, from what I understood.

**Comment by meyrevived** [comment]
@eisraeli
1. & 2. SeaLighhts weren't prepared for how Konflux people test their code - they weren't entirely ready for how and where we run our go code, they weren't ready for testing in github actions/tekton taskruns as integration tests on Konflux itself, and they kept updating the things they need us to do with more demands. This is why there are so many PRs for the same damn jira task.
3. It's set for that now.

**Comment by meyrevived** [comment]
I mentioned I will yesterday in the priorities meeting.

**Review by mshaposhnik — APPROVED** [review]

**Pull request merged**
